spring:
  profiles:
    active: dev
  timezone: UTC+08:00
  application:
    name: mars-tnc
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
#      username: configUMars
#      password: configMarsP@ss$8172

management:
  endpoints:
    web:
      exposure:
        include: refresh